sudo: required

services:
  - docker

before_install:
  - docker build -t elbor2008/multi-docker -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true elbor2008/multi-docker npm run test

after_success:
  - docker build -t elbor2008/multi-client ./client
  - docker build -t elbor2008/multi-nginx ./nginx
  - docker build -t elbor2008/multi-server ./server
  - docker build -t elbor2008/multi-worker ./worker

# login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin#
# push docker image to docker hub
  - docker push elbor2008/multi-client
  - docker push elbor2008/multi-nginx
  - docker push elbor2008/multi-server
  - docker push elbor2008/multi-worker