version: '3'
services:
  postgres:
    image: postgres
  redis:
    image: redis
  api:
    depends_on: 
      - postgres
      - redis
    build: 
      dockerfile: dockerfile.dev
      context: ./server
    volumes: 
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
  client:
    build: 
      dockerfile: dockerfile.dev
      context: ./client
  workder:
    build: 
      dockerfile: dockerfile.dev
      context: ./worker
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: dockerfile.dev
      context: ./nginx
    ports: 
      - 8000:80